### ISSUE TITLE
Used in PageTranslate/tk_translate, also source="auto" support could be neat

### ISSUE THREAD

**Issue by prof-milki** [nidhaloff/deep-translator-api#1]
* deep_translator_api version: [0.1.2](https://github.com/nidhaloff/deep-translator-api/releases/tag/v0.1.2)
* Python version: 3.8
* Operating System: Linux
* Priority: infomercial

### Description

Just a quick note that I'm using the DT API in [PageTranslate](https://freshcode.club/projects/pagetranslate.oxt) and [tk_translate](https://pypi.org/project/tk-translate/). Though I wouldn't expect many requests or users, it would show up in logs with a LibreOffice/7.x user agent or similar such. Mainly intending it as fallback for OpenOffice (stuck on Python 2.7).

![](https://imgur.com/AqAlSxU.png)

### source=auto

So, this would really be something to implement in deep-translator directly. And the API is convenient enough already. But as potential feature request: if a request carries a { source: auto } language, then applying the internal language detection would be even more practical. (Would avoid me relying on local langdetect.)

**Comment by nidhaloff** [comment]
Hi @prof-milki, yeah but source = auto will be interpreted differently depending on the translator. For instance, the Google translator would use it directly in the request, whereas other translator does not have the source = auto feature and then these can make a langdetect. If you already working on it, just open a PR and I will review it ;)

Also, since you are using the package in your projects, it would be great to give me & deep-translator some credits for it.
